package com.realtor.plugins.dao

import com.realtor.plugins.data.model.Houses

interface HousesDao {
    suspend fun insert(
        title: String,
        price: String,
        type: String,
        size: String,
        rooms: String,
        address: String,
        mls: String,
        county: String,
        city: String,
        area: Long,
        neighborhood: String,
        zip: Long,
        style: String,
        builtYear: Long,
        taxes: String,
        description: String,
        dataSource: String,
        priceHistoryDate: String,
        priceHistoryDetail: String,
        restrictions: String,
        housingOlderPersonsAct: String,
        foreclosure: Boolean,
        views: Boolean,
        shortSale: Boolean,
        newConstruction: Boolean,
        adult: Boolean,
        leaseToOwn: Boolean,
        noHoaFees: Boolean,
        furnished: Boolean,
        pets: Boolean,
        primaryOnMain: Boolean,
        airConditioning: Boolean,
        sellerFinance: Boolean,
        green: Boolean,
        fixedUpper: Boolean,
        horse: Boolean,
        golf: Boolean,
        fireplace: Boolean,
        deck: Boolean,
        garage: Boolean,
        basement: Boolean,
        pool: Boolean
    ): Houses?

    suspend fun getHouses(): List<Houses>?
    suspend fun getHousesById(id: Int): Houses?
    suspend fun deleteHouseById(id: Int): Int?
    suspend fun updateHouseById(
        id: Int,
        title: String,
        price: String,
        type: String,
        size: String,
        rooms: String,
        address: String,
        mls: String,
        county: String,
        city: String,
        area: Long,
        neighborhood: String,
        zip: Long,
        style: String,
        builtYear: Long,
        taxes: String,
        description: String,
        dataSource: String,
        priceHistoryDate: String,
        priceHistoryDetail: String,
        restrictions: String,
        housingOlderPersonsAct: String,
        foreclosure: Boolean,
        views: Boolean,
        shortSale: Boolean,
        newConstruction: Boolean,
        adult: Boolean,
        leaseToOwn: Boolean,
        noHoaFees: Boolean,
        furnished: Boolean,
        pets: Boolean,
        primaryOnMain: Boolean,
        airConditioning: Boolean,
        sellerFinance: Boolean,
        green: Boolean,
        fixedUpper: Boolean,
        horse: Boolean,
        golf: Boolean,
        fireplace: Boolean,
        deck: Boolean,
        garage: Boolean,
        basement: Boolean,
        pool: Boolean
    ): Int?
}
